-- 보드 번호(PK)
-- 제목
-- 내용
-- 작성자
-- 파일이름
-- 파일리네임
-- 파일경로
-- 파일크기
-- 조회수
-- 작성날짜
-- 수정날짜
-- 사용여부(status)

CREATE TABLE BOARD_TBL(
    BOARD_NO NUMBER PRIMARY KEY,
    BOARD_TITLE VARCHAR2(50) NOT NULL,
    BOARD_CONTENT VARCHAR2(2000) NOT NULL,
    BOARD_WRITER VARCHAR2(30) NOT NULL,
    BOARD_FILENAME VARCHAR2(100),
    BOARD_FILERENAME VARCHAR2(200),
    BOARD_FILEPATH VARCHAR2(300),
    BOARD_FILELENGTH NUMBER,
    BOARD_COUNT NUMBER,
    B_CREATE_DATE DATE DEFAULT SYSDATE,
    B_UPDATE_DATE DATE DEFAULT SYSDATE,
    B_STATUS CHAR(1) DEFAULT 'Y'
);

CREATE SEQUENCE SEQ_BOARD_NO
START WITH 1
INCREMENT BY 1
NOCYCLE
NOCACHE;

-- USER_ : 데이터 딕셔너리
SELECT * FROM USER_SEQUENCES;
SELECT * FROM BOARD_TBL;

DROP TABLE BOARD_TBL;


BEGIN
    FOR  N IN 1..200
    LOOP
        INSERT INTO BOARD_TBL
        VALUES(SEQ_BOARD_NO.NEXTVAL, '게시글'||N||'번째', N||'번째 게시글입니다', 'admin', null, null, null, null, 0, DEFAULT, DEFAULT, DEFAULT);
    END LOOP;
END;
/
commit;

SELECT * FROM BOARD_TBL ORDER BY B_UPDATE_DATE DESC;