

BEGIN 
    FOR N IN 1..200 LOOP
    LOOP
    INSERT INTO NOTICE_TBL VALUES(SEQ_NOTICE_NO.NEXTVAL, '공지사항 '||N||'번째', N||'번째 공지사항입니다', 'admin', DEFAULT, DEFAULT, NULL, NULL, NULL);
    END LOOP
END;
/

BEGIN
    FOR N IN 1..200
    LOOP
    INSERT INTO NOTICE_TBL VALUES(SEQ_NOTICE_NO.NEXTVAL, '공지사항 '||N||'번째', N||'번째 공지사항입니다', 'admin', DEFAULT, DEFAULT, NULL, NULL, NULL);
    END LOOP;
END;
/

SELECT * FROM NOTICE_TBL WHERE NOTICE_SUBJECT LIKE '%공지%';